(package "vs-electric-spacing"
         "0.1.0"
         "Add spacing around operators like Visual Studio")

(website-url "https://github.com/emacs-vs/vs-electric-spacing")
(keywords "convenience" "electric" "vs")

(package-file "vs-electric-spacing.el")

(source "jcs-elpa")
(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
